server:
    port: 7982

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

spring:
    application:
        name: service-feign

feign:
  hystrix:
    enabled: true