server:
    port: 7981

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

spring:
    application:
        name: service-consummer

feign:
  hystrix:
    enabled: true